# Generated by Django 5.2.17 on 2026-10-02 18:35

from django.db import migrations, models

def mark_existing_users_verified(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.all().update(is_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            mark_existing_users_verified,
            migrations.RunPython.noop,
        ),
    ]
