# Generated by Django 5.2.15 on 2026-10-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_socialidentity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialidentity',
            name='provider',
            field=models.CharField(choices=[('google', 'Google')], max_length=20),
        ),
    ]
