# Generated by Django 5.2.17 on 2026-09-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='area',
            field=models.CharField(blank=True, choices=[('beit_lahia', 'بيت لاهيا'), ('umm_al_nasr', 'أم النصر'), ('jabalia_camp', 'مخيم جباليا'), ('jabalia', 'جباليا'), ('beit_hanoun', 'بيت حانون'), ('gaza_city', 'غزة'), ('shati_camp', 'الشاطئ'), ('mughraqa', 'المغراقة'), ('juhr_al_dik', 'جحر الديك'), ('zahra', 'مدينة الزهرة'), ('masdar', 'المصدر'), ('nuseirat', 'النصيرات'), ('nuseirat_camp', 'مخيم النصيرات'), ('bureij', 'البريج'), ('zawayda', 'الزوايدة'), ('maghazi', 'المغازي'), ('maghazi_camp', 'مخيم المغازي'), ('wadi_salqa', 'وادي السلقا'), ('deir_al_balah_camp', 'مخيم دير البلح'), ('deir_al_balah', 'دير البلح'), ('qarara', 'القرارة'), ('khan_younis_city', 'خانيونس'), ('khan_younis_camp', 'مخيم خانيونس'), ('bani_suheila', 'بني سهيلا'), ('abasan_kabira', 'عبسان الكبيرة'), ('abasan_saghira', 'عبسان الصغيرة'), ('khuzaa', 'خزاعة'), ('fukhari', 'الفخاري'), ('rafah_city', 'رفح'), ('rafah_camp', 'مخيم رفح'), ('nasr', 'النصر'), ('shawka', 'الشوكة')], max_length=30),
        ),
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='governorate',
            field=models.CharField(blank=True, choices=[('north_gaza', 'شمال غزة'), ('gaza', 'غزة'), ('middle_gaza', 'وسط غزة'), ('khan_younis', 'خانيونس'), ('rafah', 'رفح')], max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='has_generator_line',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_main_grid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_private_well',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_solar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_water_tank',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(blank=True, choices=[('apartment', 'شقة'), ('villa', 'فيلا'), ('land', 'قطعة أرض'), ('store_room', 'حاصل'), ('shop', 'محل تجاري'), ('barracks', 'بركس')], max_length=20),
        ),
    ]
