# Generated by Django 5.2.17 on 2026-09-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_area_property_bedrooms_property_governorate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='area_sqm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
