# Generated by Django 5.2.15 on 2026-10-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_area_sqm_property_bathrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='interest_enabled',
            field=models.BooleanField(default=True),
        ),
    ]