# Generated by Django 5.2.17 on 2026-10-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_has_balcony_property_has_central_ac_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='interest_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
