# Generated by Django 5.2.17 on 2026-10-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestrequest',
            name='request_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
