# Generated by Django 5.2.17 on 2026-10-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest_requests', '0002_interestrequest_request_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestrequest',
            name='rejection_note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='interestrequest',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('property_unavailable', 'Property is no longer available'), ('payment_terms_not_compatible', 'Payment terms are not compatible'), ('rental_period_too_short', 'Rental period is too short')], max_length=30),
        ),
    ]
