# Generated by Django 5.2.17 on 2026-10-07 19:07

from django.db import migrations


def fill_request_codes(apps, schema_editor):
    InterestRequest = apps.get_model(
        'interest_requests',
        'InterestRequest',
    )

    for request in InterestRequest.objects.filter(
        request_code__isnull=True
    ).iterator():
        request.request_code = f'REQ-{request.pk:05d}'
        request.save(update_fields=['request_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('interest_requests', '0003_interestrequest_rejection_note_and_more'),
    ]

    operations = [
        migrations.RunPython(
            fill_request_codes,
            migrations.RunPython.noop,
        ),
    ]